#!/bin/sh

sed -i 's/vpn/services/g' ./luci-app-passwall/luasrc/controller/passwall.lua
sed -i 's/VPN/services/g' ./luci-app-passwall/luasrc/controller/passwall.lua
sed -i 's/vpn/services/g' ./luci-app-passwall/luasrc/model/cbi/passwall/node_config.lua
sed -i 's/vpn/services/g' ./luci-app-passwall/luasrc/model/cbi/passwall/node_list.lua
sed -i 's/vpn/services/g' ./luci-app-passwall/luasrc/model/cbi/passwall/node_subscribe.lua
sed -i 's/vpn/services/g' ./luci-app-passwall/luasrc/view/passwall/global/status.htm
sed -i 's/vpn/services/g' ./luci-app-passwall/luasrc/view/passwall/global/status2.htm
sed -i 's/vpn/services/g' ./luci-app-passwall/luasrc/view/passwall/global/tips.htm
sed -i 's/vpn/services/g' ./luci-app-passwall/luasrc/view/passwall/haproxy/status.htm
sed -i 's/vpn/services/g' ./luci-app-passwall/luasrc/view/passwall/log/log.htm
sed -i 's/vpn/services/g' ./luci-app-passwall/luasrc/view/passwall/node_list/link_add_node.htm
sed -i 's/vpn/services/g' ./luci-app-passwall/luasrc/view/passwall/node_list/node_list.htm
sed -i 's/vpn/services/g' ./luci-app-passwall/luasrc/view/passwall/other/footer.htm
sed -i 's/vpn/services/g' ./luci-app-passwall/luasrc/view/passwall/rule/brook_version.htm
sed -i 's/vpn/services/g' ./luci-app-passwall/luasrc/view/passwall/rule/kcptun_version.htm
sed -i 's/vpn/services/g' ./luci-app-passwall/luasrc/view/passwall/rule/rule_version.htm
sed -i 's/vpn/services/g' ./luci-app-passwall/luasrc/view/passwall/rule/v2ray_version.htm
